### ISSUE TITLE
Twig deprecation to fix

### ISSUE THREAD

**Issue by ghost** [Orbitale/CmsBundle#15]
Using the "Twig_Extension_GlobalsInterface" class is deprecated since Twig version 2.7, use "Twig\Extension\GlobalsInterface" instead.

**Comment by Pierstoval** [comment]
Hello, thanks for noticing the bug!

Can you provide a PR for the fix?

**Comment by ghost** [comment]
Please check

**Comment by ghost** [comment]
@Pierstoval are you going to merge it? :)

**Comment by Pierstoval** [comment]
Done 👍  Sorry I was unavailable for a while 😃
