### ISSUE TITLE
Symfony 4.x deprecations

### ISSUE THREAD

**Issue by ghost** [Orbitale/CmsBundle#19]
Guys, I resolved some more deprecation here https://github.com/Orbitale/CmsBundle/pull/18/files but that would require Symfony 4. Not sure if I should force Symfony 4.2 in composer.json.

There is still some more deprecation that I struggle to fix because it requires bigger changes:
`User Deprecated: Loading Twig templates from the "/Users/maciej.wagner/PhpstormProjects/CmsBundle/Tests/Fixtures/App/Resources/views" directory is deprecated since Symfony 4.2, use "/Users/maciej.wagner/PhpstormProjects/CmsBundle/templates" instead.`

`User Deprecated: Relying on the default value ("false") of the "twig.strict_variables" configuration option is deprecated since Symfony 4.1. You should use "%kernel.debug%" explicitly instead, which will be the new default in 5.0.`

`User Deprecated: Auto-injection of the container for "Orbitale\Bundle\CmsBundle\Controller\PageController" is deprecated since Symfony 4.2. Configure it as a service instead.`

Can you help?

**Comment by ghost** [comment]
Probably 4.x branch would be good

**Comment by ghost** [comment]
Ping

**Comment by Pierstoval** [comment]
These are deprecations that do not cause any harm, and Symfony 5 is not here yet, I will fix this when I'll have less urgent things, thanks for the reminder though :+1: :slightly_smiling_face:

**Comment by ghost** [comment]
@Pierstoval Can you create 4.x branch? I will redirect my pull request there

**Comment by Pierstoval** [comment]
4.x is now the default branch 👍 

I wish 4.x could be compatible with 4.4 and 5.0 only, since they're going to be released in two months, so we can remove all possible deprecations that will come in 4.4.

If you feel like 4.3 deprecations can be removed in the 3.x branch, feel free to submit a different PR 😉

**Comment by Pierstoval** [comment]
Fixed in #18, I'll update the rest soon :)
