### ISSUE TITLE
Working with Symfony ^5.0

### ISSUE THREAD

**Issue by aimproxy** [Orbitale/CmsBundle#21]
The command I run: `composer require orbitale/cms-bundle "4.x-dev"`

The output:
`  Problem 1
    - Installation request for orbitale/cms-bundle 4.x-dev -> satisfiable by orbitale/cms-bundle[4.x-dev].
    - orbitale/cms-bundle 4.x-dev requires symfony/asset ^4.2 -> no matching package found.
`

In my `composer.json` file the `symfony/asset` is on the ` "5.0.*"`

Can you help?

**Comment by Pierstoval** [comment]
I will take care of this soon :)

**Comment by aimproxy** [comment]
Thx, if u need help just say it! :) Also I wanna discuss with u about an ethical question of this bundle, should I open another issue? It's nothing related with symfony 5! This conversation continuous here #23 !

**Comment by Pierstoval** [comment]
Yep, another issue seems okay :)

**Comment by Pierstoval** [comment]
I'm working on this on #24 :+1:
