### ISSUE TITLE
Doctrine ResultCache

### ISSUE THREAD

**Issue by sfarkas1988** [Orbitale/CmsBundle#3]
Hey, it would be great to be able to cache the doctrine results via configuration.

**Comment by Pierstoval** [comment]
Results from which query?
There are already may configuration options for caching.

But yes, queries can be cached, if you want you can submit a PR for this :)

**Comment by sfarkas1988** [comment]
\Orbitale\Bundle\CmsBundle\Repository\PageRepository::findFrontPages
This method should use doctrine result cache optionally, this would be great. 
i overwrote your controller and cache the response object with redis for now. 
But yes, i'll write a todo for myself to create a pr some day, good idea.

**Comment by Pierstoval** [comment]
Nice :+1: 
Would just need to add some config options and declare the repository as a service.
