### ISSUE TITLE
use php8 attribute for ORM ?

### ISSUE THREAD

**Issue by Snowbaha** [Orbitale/CmsBundle#33]
Hello,

Do you plan to update the project with php8 Attribute for the entity (doctrine?)

It will be more easy to extand Page for example like this:

```<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Orbitale\Bundle\CmsBundle\Entity\Page as BasePage;
use Doctrine\ORM\Mapping as ORM;
use Orbitale\Bundle\CmsBundle\Repository\PageRepository;

#[ORM\Entity(repositoryClass: PageRepository::class)]
#[ORM\Table(name: 'cms_pages')]
class Page extends BasePage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    protected int $id;


    public function getId(): int
    {
        return $this->id;
    }
}
```

**Comment by Pierstoval** [comment]
This is an interesting proposal indeed, I haven't yet digged into how I could convert the entities in a backwards compatible manner, but maybe it can be an occasion to drop a new major version.

Do you think you can work on this? 😉

**Comment by Snowbaha** [comment]
I am still thinking about create a new one or use and update yours. We have to choice we my team what we decide to do but it will take some times.

**Comment by Pierstoval** [comment]
Feel free to drop me a private message on Twitter [@pierstoval](https://twitter.com/Pierstoval) if you need, so that we can talk about the things to do :)

**Comment by Snowbaha** [comment]
Hello, sorry for the late answer, it took me some time to discuss about all the need of our agency and we decided to created own page entity because we don't need the tree root and some other attributes.

**Comment by Pierstoval** [comment]
That's nice too! I'll close the issue then, anyone can reopen it if they need 👍
