### ISSUE TITLE
Make it work with symfony3

### ISSUE THREAD

**Issue by sfarkas1988** [Orbitale/CmsBundle#4]
Hey, maybe someday this bundle would also work with symfony3? :)

**Comment by Pierstoval** [comment]
Doesn't it work already ? :confused:

**Comment by sfarkas1988** [comment]
I got this: 

Problem 1
    - orbitale/cms-bundle v1.4.0 requires symfony/symfony ~2.3 -> no matching package found.

**Comment by Pierstoval** [comment]
I'm gonna fix this ;)

**Comment by sfarkas1988** [comment]
:+1:

**Comment by Pierstoval** [comment]
The PR #5 is on the way, I just need to fix build for PHP7 (which breaks I don't know why) and it's done :)
