### ISSUE TITLE
breadcrumbs confuse

### ISSUE THREAD

**Issue by marcosrjjunior** [Orbitale/CmsBundle#9]
:x:
![bread1](https://user-images.githubusercontent.com/5287262/27806642-20fba74a-6012-11e7-9ed4-32a183d479bb.PNG)

:x:
![bread2](https://user-images.githubusercontent.com/5287262/27806643-20fd0702-6012-11e7-978d-339b04991545.PNG)

:heavy_check_mark:
![bread3](https://user-images.githubusercontent.com/5287262/27806644-2100160e-6012-11e7-972d-7f66ee23863c.PNG)

**Comment by Pierstoval** [comment]
Fixed by #10
